export const COUNTRY_CITIES: Record<string, string[]> = {
  "USA": [
    "New York, NY","Brooklyn, NY","Queens, NY","Buffalo, NY","Rochester, NY","Syracuse, NY","Albany, NY","Yonkers, NY",
    "Los Angeles, CA","San Diego, CA","San Jose, CA","San Francisco, CA","Sacramento, CA","Fresno, CA","Long Beach, CA","Oakland, CA","Bakersfield, CA","Anaheim, CA","Riverside, CA","Stockton, CA","Irvine, CA","Chula Vista, CA","Fremont, CA","San Bernardino, CA","Modesto, CA","Fontana, CA","Moreno Valley, CA","Santa Ana, CA","Glendale, CA",
    "Chicago, IL","Aurora, IL","Joliet, IL","Naperville, IL","Rockford, IL","Springfield, IL","Peoria, IL","Elgin, IL",
    "Houston, TX","San Antonio, TX","Dallas, TX","Austin, TX","Fort Worth, TX","El Paso, TX","Arlington, TX","Corpus Christi, TX","Plano, TX","Laredo, TX","Lubbock, TX","Irving, TX","Garland, TX","Amarillo, TX","Frisco, TX","McKinney, TX",
    "Phoenix, AZ","Tucson, AZ","Mesa, AZ","Scottsdale, AZ","Tempe, AZ","Chandler, AZ","Gilbert, AZ","Glendale, AZ",
    "Philadelphia, PA","Pittsburgh, PA","Allentown, PA","Erie, PA","Reading, PA",
    "Jacksonville, FL","Miami, FL","Tampa, FL","Orlando, FL","St. Petersburg, FL","Hialeah, FL","Port St. Lucie, FL","Cape Coral, FL","Tallahassee, FL","Fort Lauderdale, FL","Pembroke Pines, FL","Hollywood, FL","Gainesville, FL","Clearwater, FL",
    "Columbus, OH","Cleveland, OH","Cincinnati, OH","Toledo, OH","Akron, OH","Dayton, OH",
    "Indianapolis, IN","Fort Wayne, IN","Evansville, IN","South Bend, IN","Carmel, IN",
    "Charlotte, NC","Raleigh, NC","Greensboro, NC","Durham, NC","Winston-Salem, NC","Fayetteville, NC","Cary, NC",
    "Nashville, TN","Memphis, TN","Knoxville, TN","Chattanooga, TN","Clarksville, TN",
    "Seattle, WA","Spokane, WA","Tacoma, WA","Vancouver, WA","Bellevue, WA","Kent, WA","Everett, WA",
    "Denver, CO","Colorado Springs, CO","Aurora, CO","Fort Collins, CO","Lakewood, CO","Thornton, CO","Arvada, CO","Westminster, CO","Pueblo, CO",
    "Las Vegas, NV","Henderson, NV","Reno, NV","North Las Vegas, NV","Sparks, NV",
    "Atlanta, GA","Columbus, GA","Savannah, GA","Augusta, GA","Macon, GA","Warner Robins, GA",
    "Detroit, MI","Grand Rapids, MI","Warren, MI","Sterling Heights, MI","Lansing, MI","Ann Arbor, MI","Flint, MI","Dearborn, MI",
    "Minneapolis, MN","St. Paul, MN","Rochester, MN","Duluth, MN","Bloomington, MN","Brooklyn Park, MN",
    "Kansas City, MO","St. Louis, MO","Springfield, MO","Columbia, MO","Independence, MO","Lee's Summit, MO",
    "Virginia Beach, VA","Norfolk, VA","Chesapeake, VA","Richmond, VA","Newport News, VA","Alexandria, VA","Hampton, VA",
    "Baltimore, MD","Frederick, MD","Rockville, MD","Gaithersburg, MD","Bowie, MD",
    "Boston, MA","Worcester, MA","Springfield, MA","Lowell, MA","Cambridge, MA","New Bedford, MA",
    "Portland, OR","Salem, OR","Eugene, OR","Gresham, OR","Hillsboro, OR","Beaverton, OR",
    "Louisville, KY","Lexington, KY","Bowling Green, KY","Owensboro, KY",
    "Oklahoma City, OK","Tulsa, OK","Norman, OK","Broken Arrow, OK","Edmond, OK","Lawton, OK",
    "Milwaukee, WI","Madison, WI","Green Bay, WI","Kenosha, WI","Racine, WI","Appleton, WI",
    "Albuquerque, NM","Santa Fe, NM","Las Cruces, NM","Rio Rancho, NM",
    "Omaha, NE","Lincoln, NE","Bellevue, NE",
    "Salt Lake City, UT","Provo, UT","West Valley City, UT","West Jordan, UT","Orem, UT","Sandy, UT",
    "New Orleans, LA","Baton Rouge, LA","Shreveport, LA","Metairie, LA","Lafayette, LA","Lake Charles, LA",
    "Des Moines, IA","Cedar Rapids, IA","Davenport, IA","Sioux City, IA",
    "Wichita, KS","Overland Park, KS","Kansas City, KS","Topeka, KS","Olathe, KS",
    "Birmingham, AL","Montgomery, AL","Mobile, AL","Huntsville, AL","Tuscaloosa, AL",
    "Newark, NJ","Jersey City, NJ","Paterson, NJ","Elizabeth, NJ","Edison, NJ","Trenton, NJ",
    "Washington, DC",
    "Memphis, TN","Nashville, TN",
    "Minneapolis, MN","St. Paul, MN",
    "Anchorage, AK","Honolulu, HI","Charleston, WV","Huntington, WV",
    "Sioux Falls, SD","Rapid City, SD","Fargo, ND","Bismarck, ND","Billings, MT","Missoula, MT",
    "Little Rock, AR","Fort Smith, AR","Fayetteville, AR",
    "Jackson, MS","Gulfport, MS","Southaven, MS","Hattiesburg, MS",
    "Providence, RI","Bridgeport, CT","New Haven, CT","Hartford, CT","Stamford, CT",
    "Wilmington, DE","Dover, DE","Manchester, NH","Nashua, NH","Portland, ME","Burlington, VT",
    "Columbia, SC","Charleston, SC","North Charleston, SC","Greenville, SC",
    "Cheyenne, WY","Casper, WY","Boise, ID","Meridian, ID","Nampa, ID",
  ],
  "Canada": ["Toronto, ON","Vancouver, BC","Montreal, QC","Calgary, AB","Ottawa, ON","Edmonton, AB","Winnipeg, MB","Hamilton, ON","Quebec City, QC","Halifax, NS","Victoria, BC","London, ON","Saskatoon, SK","Regina, SK","St. John's, NL","Kelowna, BC","Abbotsford, BC","Sudbury, ON","Windsor, ON","Barrie, ON","Gatineau, QC","Longueuil, QC","Laval, QC","Burnaby, BC","Surrey, BC"],
  "UK": ["London","Birmingham","Manchester","Leeds","Glasgow","Sheffield","Bradford","Edinburgh","Liverpool","Bristol","Cardiff","Leicester","Nottingham","Coventry","Belfast","Derby","Plymouth","Stoke-on-Trent","Wolverhampton","Southampton","Brighton","Portsmouth","Reading","Oxford","Cambridge","Bath","York","Newcastle upon Tyne","Sunderland","Middlesbrough"],
  "Australia": ["Sydney, NSW","Melbourne, VIC","Brisbane, QLD","Perth, WA","Adelaide, SA","Gold Coast, QLD","Newcastle, NSW","Canberra, ACT","Wollongong, NSW","Hobart, TAS","Geelong, VIC","Townsville, QLD","Cairns, QLD","Darwin, NT","Ballarat, VIC","Toowoomba, QLD","Bendigo, VIC","Launceston, TAS","Albury, NSW","Mackay, QLD"],
  "UAE": ["Dubai","Abu Dhabi","Sharjah","Ajman","Ras Al Khaimah","Fujairah","Umm Al Quwain","Al Ain","Khalifa City","Mussafah"],
  "India": ["Mumbai","Delhi","Bangalore","Hyderabad","Chennai","Kolkata","Pune","Ahmedabad","Surat","Jaipur","Lucknow","Kanpur","Nagpur","Visakhapatnam","Indore","Thane","Bhopal","Patna","Vadodara","Ghaziabad","Ludhiana","Agra","Nashik","Faridabad","Meerut","Rajkot","Varanasi","Srinagar","Aurangabad","Dhanbad"],
  "Germany": ["Berlin","Hamburg","Munich","Cologne","Frankfurt","Stuttgart","Düsseldorf","Dortmund","Essen","Leipzig","Bremen","Dresden","Hanover","Nuremberg","Duisburg","Bochum","Wuppertal","Bielefeld","Bonn","Mannheim","Karlsruhe","Augsburg","Wiesbaden","Mönchengladbach","Gelsenkirchen","Aachen","Braunschweig","Kiel","Chemnitz","Halle"],
  "France": ["Paris","Marseille","Lyon","Toulouse","Nice","Nantes","Strasbourg","Montpellier","Bordeaux","Lille","Rennes","Reims","Saint-Étienne","Toulon","Grenoble","Dijon","Angers","Nîmes","Villeurbanne","Le Mans","Aix-en-Provence","Brest","Clermont-Ferrand","Tours","Amiens","Limoges","Perpignan","Metz","Besançon","Orléans"],
  "Netherlands": ["Amsterdam","Rotterdam","The Hague","Utrecht","Eindhoven","Groningen","Tilburg","Almere","Breda","Nijmegen","Enschede","Haarlem","Arnhem","Zaanstad","Amersfoort","Apeldoorn","Zwolle","Leiden","Dordrecht","Haarlemmermeer"],
  "Singapore": ["Singapore","Jurong","Tampines","Woodlands","Hougang","Bedok","Choa Chu Kang","Ang Mo Kio","Toa Payoh","Buona Vista"],
  "New Zealand": ["Auckland","Wellington","Christchurch","Hamilton","Tauranga","Dunedin","Palmerston North","Nelson","Rotorua","New Plymouth","Napier","Hastings","Invercargill","Whangarei","Upper Hutt"],
  "Ireland": ["Dublin","Cork","Limerick","Galway","Waterford","Drogheda","Dundalk","Swords","Bray","Navan","Kilkenny","Ennis","Carlow","Tralee","Sligo"],
  "South Africa": ["Johannesburg","Cape Town","Durban","Pretoria","Port Elizabeth","Bloemfontein","East London","Pietermaritzburg","Polokwane","Kimberley","Nelspruit","Rustenburg","George","Witbank","Vereeniging"],
  "Philippines": ["Manila","Quezon City","Cebu","Davao","Caloocan","Zamboanga","Taguig","Antipolo","Pasig","Makati","Parañaque","Valenzuela","Las Piñas","Mandaluyong","Marikina"],
  "Malaysia": ["Kuala Lumpur","George Town","Ipoh","Shah Alam","Petaling Jaya","Kota Kinabalu","Kuching","Johor Bahru","Subang Jaya","Klang","Malacca City","Alor Setar","Seremban","Kota Bharu","Sandakan"],
  "Saudi Arabia": ["Riyadh","Jeddah","Mecca","Medina","Dammam","Al Khobar","Tabuk","Buraidah","Khamis Mushait","Al Hufuf","Abha","Hail","Najran","Jubail","Yanbu"],
  "Pakistan": ["Karachi","Lahore","Faisalabad","Rawalpindi","Islamabad","Gujranwala","Peshawar","Multan","Hyderabad","Quetta","Sialkot","Bahawalpur","Sargodha","Dera Ghazi Khan","Sheikhupura"],
  "Nigeria": ["Lagos","Kano","Ibadan","Abuja","Port Harcourt","Benin City","Maiduguri","Zaria","Jos","Kaduna","Enugu","Warri","Aba","Onitsha","Calabar"],
  "Kenya": ["Nairobi","Mombasa","Kisumu","Nakuru","Eldoret","Thika","Malindi","Kitale","Garissa","Kakamega","Machakos","Nyeri","Meru","Kisii","Kericho"],
  "Brazil": ["São Paulo","Rio de Janeiro","Brasília","Salvador","Fortaleza","Belo Horizonte","Manaus","Curitiba","Recife","Porto Alegre","Belém","Goiânia","Guarulhos","Campinas","São Luís","Maceió","Natal","Teresina","Campo Grande","João Pessoa"],
  "Mexico": ["Mexico City","Guadalajara","Monterrey","Puebla","Tijuana","León","Ciudad Juárez","Zapopan","Mérida","Cancún","Culiacán","Aguascalientes","Hermosillo","Chihuahua","San Luis Potosí","Querétaro","Morelia","Veracruz","Mexicali","Naucalpan"],
  "Spain": ["Madrid","Barcelona","Valencia","Seville","Zaragoza","Málaga","Murcia","Palma","Las Palmas","Bilbao","Alicante","Córdoba","Valladolid","Vigo","Gijón","Granada","Hospitalet","A Coruña","Vitoria-Gasteiz","Santa Cruz de Tenerife"],
  "Italy": ["Rome","Milan","Naples","Turin","Palermo","Genoa","Bologna","Florence","Bari","Catania","Venice","Verona","Messina","Padua","Trieste","Taranto","Brescia","Parma","Reggio Calabria","Modena"],
  "Portugal": ["Lisbon","Porto","Braga","Coimbra","Funchal","Setúbal","Amadora","Almada","Famalicão","Agualva-Cacém","Vila Nova de Gaia","Loures","Cascais","Sintra","Oeiras"],
  "Sweden": ["Stockholm","Gothenburg","Malmö","Uppsala","Västerås","Örebro","Linköping","Helsingborg","Jönköping","Norrköping","Lund","Umeå","Gävle","Borås","Södertälje"],
  "Norway": ["Oslo","Bergen","Trondheim","Stavanger","Drammen","Fredrikstad","Kristiansand","Sandnes","Ålesund","Tromsø","Sarpsborg","Skien","Akershus","Halden","Hamar"],
  "Denmark": ["Copenhagen","Aarhus","Odense","Aalborg","Esbjerg","Randers","Kolding","Horsens","Vejle","Roskilde","Herning","Helsingør","Silkeborg","Næstved","Fredericia"],
  "Switzerland": ["Zurich","Geneva","Basel","Bern","Lausanne","Winterthur","Lucerne","St. Gallen","Lugano","Biel","Thun","Köniz","La Chaux-de-Fonds","Schaffhausen","Fribourg"],
  "Austria": ["Vienna","Graz","Linz","Salzburg","Innsbruck","Klagenfurt","Villach","Wels","Sankt Pölten","Steyr","Dornbirn","Wiener Neustadt","Feldkirch","Bregenz","Leonding"],
  "Poland": ["Warsaw","Kraków","Łódź","Wrocław","Poznań","Gdańsk","Szczecin","Bydgoszcz","Lublin","Białystok","Katowice","Gdynia","Częstochowa","Radom","Sosnowiec"],
  "Czech Republic": ["Prague","Brno","Ostrava","Plzeň","Liberec","Olomouc","Ústí nad Labem","České Budějovice","Hradec Králové","Pardubice","Havířov","Zlín","Kladno","Most","Karviná"],
  "Hungary": ["Budapest","Debrecen","Miskolc","Szeged","Pécs","Győr","Nyíregyháza","Kecskemét","Székesfehérvár","Szombathely","Szolnok","Tatabánya","Kaposvár","Érd","Veszprém"],
  "Romania": ["Bucharest","Cluj-Napoca","Timișoara","Iași","Constanța","Craiova","Brașov","Galați","Ploiești","Oradea","Brăila","Bacău","Arad","Pitești","Sibiu"],
  "Greece": ["Athens","Thessaloniki","Patras","Heraklion","Larissa","Volos","Ioannina","Chania","Chalcis","Agrinion","Katerini","Trikala","Lamia","Alexandroupoli","Kavala"],
  "Turkey": ["Istanbul","Ankara","İzmir","Bursa","Adana","Gaziantep","Konya","Antalya","Kayseri","Diyarbakır","Mersin","Eskişehir","Samsun","Denizli","Şanlıurfa"],
  "Egypt": ["Cairo","Alexandria","Giza","Shubra El-Kheima","Port Said","Suez","Luxor","Mansoura","El-Mahalla El-Kubra","Tanta","Asyut","Ismailia","Faiyum","Zagazig","Aswan"],
  "Japan": ["Tokyo","Yokohama","Osaka","Nagoya","Sapporo","Fukuoka","Kobe","Kawasaki","Kyoto","Saitama","Hiroshima","Sendai","Kitakyushu","Chiba","Sakai"],
  "South Korea": ["Seoul","Busan","Incheon","Daegu","Daejeon","Gwangju","Suwon","Ulsan","Changwon","Seongnam","Goyang","Yongin","Bucheon","Cheongju","Ansan"],
  "China": ["Shanghai","Beijing","Guangzhou","Shenzhen","Chengdu","Chongqing","Hangzhou","Wuhan","Xi'an","Tianjin","Nanjing","Dongguan","Shenyang","Qingdao","Zhengzhou"],
  "Indonesia": ["Jakarta","Surabaya","Bandung","Medan","Bekasi","Palembang","Makassar","Semarang","Depok","Tangerang","South Tangerang","Bogor","Pekanbaru","Batam","Padang"],
  "Thailand": ["Bangkok","Chiang Mai","Pattaya","Phuket","Khon Kaen","Hat Yai","Nakhon Ratchasima","Udon Thani","Nonthaburi","Pak Kret","Chon Buri","Samut Prakan","Rayong","Krabi","Kanchanaburi"],
  "Vietnam": ["Ho Chi Minh City","Hanoi","Da Nang","Haiphong","Cần Thơ","Biên Hòa","Nha Trang","Buôn Ma Thuột","Vũng Tàu","Quy Nhơn","Long Xuyên","Huế","Mỹ Tho","Rạch Giá","Đà Lạt"],
};

export const ALL_COUNTRIES = Object.keys(COUNTRY_CITIES).sort();

// Number of top cities pre-selected by default per country
export const DEFAULT_CITY_COUNT = 30;

export function getDefaultCities(country: string): string[] {
  return (COUNTRY_CITIES[country] ?? []).slice(0, DEFAULT_CITY_COUNT);
}
